# Generated by Django 3.1.2 on 2020-10-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('imdb_title_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
                ('date_published', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=45)),
                ('language', models.CharField(max_length=45)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('production_company', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('avg_vote', models.CharField(max_length=20)),
                ('votes', models.CharField(max_length=20)),
                ('budget', models.CharField(max_length=30)),
                ('usa_gross_income', models.CharField(max_length=45)),
                ('worldwide_gross_income', models.CharField(max_length=45)),
                ('metascore', models.CharField(max_length=45)),
                ('reviews_from_users', models.CharField(max_length=45)),
                ('reviews_from_critics', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=65, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
