# Generated by Django 3.1.2 on 2020-10-16 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfavoritemovies_usersuggestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersuggestions',
            name='imdb_title',
        ),
        migrations.RemoveField(
            model_name='usersuggestions',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserFavoriteMovies',
        ),
        migrations.DeleteModel(
            name='UserSuggestions',
        ),
    ]
