# Generated by Django 3.1.2 on 2020-10-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userfavoritemovies_usersuggestions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoritemovies',
            unique_together={('user', 'imdb_title')},
        ),
        migrations.AlterUniqueTogether(
            name='usersuggestions',
            unique_together={('user', 'imdb_title')},
        ),
    ]
