# Generated by Django 3.1.2 on 2020-10-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201016_2006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfavoritemovies',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfavoritemovies',
            name='imdb_title',
        ),
        migrations.RemoveField(
            model_name='userfavoritemovies',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usersuggestions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usersuggestions',
            name='imdb_title',
        ),
        migrations.RemoveField(
            model_name='usersuggestions',
            name='user',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='UserFavoriteMovies',
        ),
        migrations.DeleteModel(
            name='UserSuggestions',
        ),
    ]
